[project]
name = "bingsearch-mcp"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "fake-useragent>=2.2.0",
    "mcp[cli]>=1.25.0",
    "requests>=2.32.5",
    "trafilatura>=2.0.0",
]
